// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: client.proto

package orc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_NONE_PROTOCOL          Protocol = 0
	Protocol_MOVE_JOG_REQ           Protocol = 1
	Protocol_ENTER_PLAYER_NOTI      Protocol = 2
	Protocol_WELCOME_PLAYER_NOTI    Protocol = 3
	Protocol_LEAVE_PLAYER_NOTI      Protocol = 4
	Protocol_MOVE_OBJECT_NOTI       Protocol = 5
	Protocol_ENTER_PROJECTILE_NOTI  Protocol = 6
	Protocol_PROJECTILE_ATTACK_NOTI Protocol = 7
	Protocol_SHOOT_PROJECTILE_REQ   Protocol = 8
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "NONE_PROTOCOL",
		1: "MOVE_JOG_REQ",
		2: "ENTER_PLAYER_NOTI",
		3: "WELCOME_PLAYER_NOTI",
		4: "LEAVE_PLAYER_NOTI",
		5: "MOVE_OBJECT_NOTI",
		6: "ENTER_PROJECTILE_NOTI",
		7: "PROJECTILE_ATTACK_NOTI",
		8: "SHOOT_PROJECTILE_REQ",
	}
	Protocol_value = map[string]int32{
		"NONE_PROTOCOL":          0,
		"MOVE_JOG_REQ":           1,
		"ENTER_PLAYER_NOTI":      2,
		"WELCOME_PLAYER_NOTI":    3,
		"LEAVE_PLAYER_NOTI":      4,
		"MOVE_OBJECT_NOTI":       5,
		"ENTER_PROJECTILE_NOTI":  6,
		"PROJECTILE_ATTACK_NOTI": 7,
		"SHOOT_PROJECTILE_REQ":   8,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

type Direction int32

const (
	Direction_NONE_DIR   Direction = 0
	Direction_NORTH      Direction = 1
	Direction_NORTH_EAST Direction = 2
	Direction_EAST       Direction = 3
	Direction_EAST_SOUTH Direction = 4
	Direction_SOUTH      Direction = 5
	Direction_SOUTH_WEST Direction = 6
	Direction_WEST       Direction = 7
	Direction_WEST_NORTH Direction = 8
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "NONE_DIR",
		1: "NORTH",
		2: "NORTH_EAST",
		3: "EAST",
		4: "EAST_SOUTH",
		5: "SOUTH",
		6: "SOUTH_WEST",
		7: "WEST",
		8: "WEST_NORTH",
	}
	Direction_value = map[string]int32{
		"NONE_DIR":   0,
		"NORTH":      1,
		"NORTH_EAST": 2,
		"EAST":       3,
		"EAST_SOUTH": 4,
		"SOUTH":      5,
		"SOUTH_WEST": 6,
		"WEST":       7,
		"WEST_NORTH": 8,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[1].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[1]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

type PlayerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X   float64   `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y   float64   `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Dir Direction `protobuf:"varint,4,opt,name=dir,proto3,enum=orc.Direction" json:"dir,omitempty"`
}

func (x *PlayerMessage) Reset() {
	*x = PlayerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMessage) ProtoMessage() {}

func (x *PlayerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMessage.ProtoReflect.Descriptor instead.
func (*PlayerMessage) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerMessage) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerMessage) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerMessage) GetDir() Direction {
	if x != nil {
		return x.Dir
	}
	return Direction_NONE_DIR
}

type ProjectileMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X     float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y     float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Angle int32   `protobuf:"varint,4,opt,name=angle,proto3" json:"angle,omitempty"`
}

func (x *ProjectileMessage) Reset() {
	*x = ProjectileMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectileMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectileMessage) ProtoMessage() {}

func (x *ProjectileMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectileMessage.ProtoReflect.Descriptor instead.
func (*ProjectileMessage) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectileMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectileMessage) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProjectileMessage) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ProjectileMessage) GetAngle() int32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type MoveJogReqMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dir Direction `protobuf:"varint,1,opt,name=dir,proto3,enum=orc.Direction" json:"dir,omitempty"`
}

func (x *MoveJogReqMessage) Reset() {
	*x = MoveJogReqMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveJogReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveJogReqMessage) ProtoMessage() {}

func (x *MoveJogReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveJogReqMessage.ProtoReflect.Descriptor instead.
func (*MoveJogReqMessage) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

func (x *MoveJogReqMessage) GetDir() Direction {
	if x != nil {
		return x.Dir
	}
	return Direction_NONE_DIR
}

type EnterPlayerNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *PlayerMessage `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *EnterPlayerNotiMessage) Reset() {
	*x = EnterPlayerNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterPlayerNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterPlayerNotiMessage) ProtoMessage() {}

func (x *EnterPlayerNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterPlayerNotiMessage.ProtoReflect.Descriptor instead.
func (*EnterPlayerNotiMessage) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *EnterPlayerNotiMessage) GetPlayer() *PlayerMessage {
	if x != nil {
		return x.Player
	}
	return nil
}

type EnterProjectileNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Projectile *ProjectileMessage `protobuf:"bytes,1,opt,name=projectile,proto3" json:"projectile,omitempty"`
}

func (x *EnterProjectileNotiMessage) Reset() {
	*x = EnterProjectileNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterProjectileNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterProjectileNotiMessage) ProtoMessage() {}

func (x *EnterProjectileNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterProjectileNotiMessage.ProtoReflect.Descriptor instead.
func (*EnterProjectileNotiMessage) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *EnterProjectileNotiMessage) GetProjectile() *ProjectileMessage {
	if x != nil {
		return x.Projectile
	}
	return nil
}

type WelcomePlayerNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyId    int64            `protobuf:"varint,1,opt,name=my_id,json=myId,proto3" json:"my_id,omitempty"`
	Players []*PlayerMessage `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *WelcomePlayerNotiMessage) Reset() {
	*x = WelcomePlayerNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomePlayerNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomePlayerNotiMessage) ProtoMessage() {}

func (x *WelcomePlayerNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomePlayerNotiMessage.ProtoReflect.Descriptor instead.
func (*WelcomePlayerNotiMessage) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *WelcomePlayerNotiMessage) GetMyId() int64 {
	if x != nil {
		return x.MyId
	}
	return 0
}

func (x *WelcomePlayerNotiMessage) GetPlayers() []*PlayerMessage {
	if x != nil {
		return x.Players
	}
	return nil
}

type LeavePlayerNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LeavePlayerNotiMessage) Reset() {
	*x = LeavePlayerNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeavePlayerNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeavePlayerNotiMessage) ProtoMessage() {}

func (x *LeavePlayerNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeavePlayerNotiMessage.ProtoReflect.Descriptor instead.
func (*LeavePlayerNotiMessage) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

func (x *LeavePlayerNotiMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MoveObjectNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*MoveObjectNotiMessage_Object `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *MoveObjectNotiMessage) Reset() {
	*x = MoveObjectNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveObjectNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveObjectNotiMessage) ProtoMessage() {}

func (x *MoveObjectNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveObjectNotiMessage.ProtoReflect.Descriptor instead.
func (*MoveObjectNotiMessage) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7}
}

func (x *MoveObjectNotiMessage) GetObjects() []*MoveObjectNotiMessage_Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type ProjectileAttackNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId     int64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ProjectileId int64 `protobuf:"varint,2,opt,name=projectile_id,json=projectileId,proto3" json:"projectile_id,omitempty"`
}

func (x *ProjectileAttackNotiMessage) Reset() {
	*x = ProjectileAttackNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectileAttackNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectileAttackNotiMessage) ProtoMessage() {}

func (x *ProjectileAttackNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectileAttackNotiMessage.ProtoReflect.Descriptor instead.
func (*ProjectileAttackNotiMessage) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectileAttackNotiMessage) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ProjectileAttackNotiMessage) GetProjectileId() int64 {
	if x != nil {
		return x.ProjectileId
	}
	return 0
}

type ShootProjectileReqMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Angle int32 `protobuf:"varint,1,opt,name=angle,proto3" json:"angle,omitempty"`
}

func (x *ShootProjectileReqMessage) Reset() {
	*x = ShootProjectileReqMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootProjectileReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootProjectileReqMessage) ProtoMessage() {}

func (x *ShootProjectileReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootProjectileReqMessage.ProtoReflect.Descriptor instead.
func (*ShootProjectileReqMessage) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{9}
}

func (x *ShootProjectileReqMessage) GetAngle() int32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type MoveObjectNotiMessage_Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X   float64   `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y   float64   `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Dir Direction `protobuf:"varint,4,opt,name=dir,proto3,enum=orc.Direction" json:"dir,omitempty"`
}

func (x *MoveObjectNotiMessage_Object) Reset() {
	*x = MoveObjectNotiMessage_Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveObjectNotiMessage_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveObjectNotiMessage_Object) ProtoMessage() {}

func (x *MoveObjectNotiMessage_Object) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveObjectNotiMessage_Object.ProtoReflect.Descriptor instead.
func (*MoveObjectNotiMessage_Object) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7, 0}
}

func (x *MoveObjectNotiMessage_Object) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MoveObjectNotiMessage_Object) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveObjectNotiMessage_Object) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MoveObjectNotiMessage_Object) GetDir() Direction {
	if x != nil {
		return x.Dir
	}
	return Direction_NONE_DIR
}

var File_client_proto protoreflect.FileDescriptor

var file_client_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x6f, 0x72, 0x63, 0x22, 0x5d, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79,
	0x12, 0x20, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e,
	0x6f, 0x72, 0x63, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x64,
	0x69, 0x72, 0x22, 0x55, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x01, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x22, 0x35, 0x0a, 0x11, 0x4d, 0x6f, 0x76,
	0x65, 0x4a, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20,
	0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6f, 0x72,
	0x63, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x64, 0x69, 0x72,
	0x22, 0x44, 0x0a, 0x16, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e,
	0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x72, 0x63,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x54, 0x0a, 0x1a, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x72, 0x63, 0x2e, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x22, 0x5d, 0x0a, 0x18,
	0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x74,
	0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x79, 0x49, 0x64, 0x12, 0x2c, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6f, 0x72, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x15, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x3b, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x6f, 0x72, 0x63, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x1a, 0x56, 0x0a, 0x06,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x01, 0x79, 0x12, 0x20, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0e, 0x2e, 0x6f, 0x72, 0x63, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x03, 0x64, 0x69, 0x72, 0x22, 0x5f, 0x0a, 0x1b, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6c, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x19, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x2a, 0xdd, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x4e, 0x45, 0x5f, 0x50, 0x52,
	0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x4f, 0x56, 0x45,
	0x5f, 0x4a, 0x4f, 0x47, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x4e,
	0x54, 0x45, 0x52, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10,
	0x02, 0x12, 0x17, 0x0a, 0x13, 0x57, 0x45, 0x4c, 0x43, 0x4f, 0x4d, 0x45, 0x5f, 0x50, 0x4c, 0x41,
	0x59, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x45,
	0x41, 0x56, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10,
	0x04, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54,
	0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10, 0x05, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x4e, 0x54, 0x45, 0x52,
	0x5f, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x49, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x49,
	0x10, 0x06, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x49, 0x4c, 0x45,
	0x5f, 0x41, 0x54, 0x54, 0x41, 0x43, 0x4b, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10, 0x07, 0x12, 0x18,
	0x0a, 0x14, 0x53, 0x48, 0x4f, 0x4f, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x49,
	0x4c, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x08, 0x2a, 0x83, 0x01, 0x0a, 0x09, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x4e, 0x45, 0x5f, 0x44,
	0x49, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x5f, 0x45, 0x41, 0x53, 0x54, 0x10, 0x02, 0x12,
	0x08, 0x0a, 0x04, 0x45, 0x41, 0x53, 0x54, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x41, 0x53,
	0x54, 0x5f, 0x53, 0x4f, 0x55, 0x54, 0x48, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x4f, 0x55,
	0x54, 0x48, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x4f, 0x55, 0x54, 0x48, 0x5f, 0x57, 0x45,
	0x53, 0x54, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x45, 0x53, 0x54, 0x10, 0x07, 0x12, 0x0e,
	0x0a, 0x0a, 0x57, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x10, 0x08, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x6f, 0x72, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData = file_client_proto_rawDesc
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_proto_rawDescData)
	})
	return file_client_proto_rawDescData
}

var file_client_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_client_proto_goTypes = []interface{}{
	(Protocol)(0),                        // 0: orc.Protocol
	(Direction)(0),                       // 1: orc.Direction
	(*PlayerMessage)(nil),                // 2: orc.PlayerMessage
	(*ProjectileMessage)(nil),            // 3: orc.ProjectileMessage
	(*MoveJogReqMessage)(nil),            // 4: orc.MoveJogReqMessage
	(*EnterPlayerNotiMessage)(nil),       // 5: orc.EnterPlayerNotiMessage
	(*EnterProjectileNotiMessage)(nil),   // 6: orc.EnterProjectileNotiMessage
	(*WelcomePlayerNotiMessage)(nil),     // 7: orc.WelcomePlayerNotiMessage
	(*LeavePlayerNotiMessage)(nil),       // 8: orc.LeavePlayerNotiMessage
	(*MoveObjectNotiMessage)(nil),        // 9: orc.MoveObjectNotiMessage
	(*ProjectileAttackNotiMessage)(nil),  // 10: orc.ProjectileAttackNotiMessage
	(*ShootProjectileReqMessage)(nil),    // 11: orc.ShootProjectileReqMessage
	(*MoveObjectNotiMessage_Object)(nil), // 12: orc.MoveObjectNotiMessage.Object
}
var file_client_proto_depIdxs = []int32{
	1,  // 0: orc.PlayerMessage.dir:type_name -> orc.Direction
	1,  // 1: orc.MoveJogReqMessage.dir:type_name -> orc.Direction
	2,  // 2: orc.EnterPlayerNotiMessage.player:type_name -> orc.PlayerMessage
	3,  // 3: orc.EnterProjectileNotiMessage.projectile:type_name -> orc.ProjectileMessage
	2,  // 4: orc.WelcomePlayerNotiMessage.players:type_name -> orc.PlayerMessage
	12, // 5: orc.MoveObjectNotiMessage.objects:type_name -> orc.MoveObjectNotiMessage.Object
	1,  // 6: orc.MoveObjectNotiMessage.Object.dir:type_name -> orc.Direction
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectileMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveJogReqMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterPlayerNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterProjectileNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WelcomePlayerNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeavePlayerNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveObjectNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectileAttackNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootProjectileReqMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveObjectNotiMessage_Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		EnumInfos:         file_client_proto_enumTypes,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_rawDesc = nil
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
