// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.6
// source: orc/client.proto

package orc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request int32

const (
	Request_NONE_REQUEST         Request = 0
	Request_MOVE_JOG_REQ         Request = 1
	Request_SHOOT_PROJECTILE_REQ Request = 2
	Request_ATTACK_REQ           Request = 3
	Request_DEFENCE_REQ          Request = 4
	Request_LOGIN_REQ            Request = 5
)

// Enum value maps for Request.
var (
	Request_name = map[int32]string{
		0: "NONE_REQUEST",
		1: "MOVE_JOG_REQ",
		2: "SHOOT_PROJECTILE_REQ",
		3: "ATTACK_REQ",
		4: "DEFENCE_REQ",
		5: "LOGIN_REQ",
	}
	Request_value = map[string]int32{
		"NONE_REQUEST":         0,
		"MOVE_JOG_REQ":         1,
		"SHOOT_PROJECTILE_REQ": 2,
		"ATTACK_REQ":           3,
		"DEFENCE_REQ":          4,
		"LOGIN_REQ":            5,
	}
)

func (x Request) Enum() *Request {
	p := new(Request)
	*p = x
	return p
}

func (x Request) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request) Descriptor() protoreflect.EnumDescriptor {
	return file_orc_client_proto_enumTypes[0].Descriptor()
}

func (Request) Type() protoreflect.EnumType {
	return &file_orc_client_proto_enumTypes[0]
}

func (x Request) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request.Descriptor instead.
func (Request) EnumDescriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{0}
}

type Notification int32

const (
	Notification_NONE_NOTI                  Notification = 0
	Notification_ENTER_PLAYER_NOTI          Notification = 1
	Notification_WELCOME_PLAYER_NOTI        Notification = 2
	Notification_LEAVE_OBJECT_NOTI          Notification = 3
	Notification_MOVE_OBJECT_NOTI           Notification = 4
	Notification_ENTER_PROJECTILE_NOTI      Notification = 5
	Notification_PROJECTILE_ATTACK_NOTI     Notification = 6
	Notification_ATTACK_PLAYER_NOTI         Notification = 7
	Notification_PLAYER_ATTACKED_NOTI       Notification = 8
	Notification_PLAYER_DEFENCE_NOTI        Notification = 9
	Notification_PLAYER_ATTACK_DEFENCE_NOTI Notification = 10
	Notification_LOGIN_NOTI                 Notification = 11
)

// Enum value maps for Notification.
var (
	Notification_name = map[int32]string{
		0:  "NONE_NOTI",
		1:  "ENTER_PLAYER_NOTI",
		2:  "WELCOME_PLAYER_NOTI",
		3:  "LEAVE_OBJECT_NOTI",
		4:  "MOVE_OBJECT_NOTI",
		5:  "ENTER_PROJECTILE_NOTI",
		6:  "PROJECTILE_ATTACK_NOTI",
		7:  "ATTACK_PLAYER_NOTI",
		8:  "PLAYER_ATTACKED_NOTI",
		9:  "PLAYER_DEFENCE_NOTI",
		10: "PLAYER_ATTACK_DEFENCE_NOTI",
		11: "LOGIN_NOTI",
	}
	Notification_value = map[string]int32{
		"NONE_NOTI":                  0,
		"ENTER_PLAYER_NOTI":          1,
		"WELCOME_PLAYER_NOTI":        2,
		"LEAVE_OBJECT_NOTI":          3,
		"MOVE_OBJECT_NOTI":           4,
		"ENTER_PROJECTILE_NOTI":      5,
		"PROJECTILE_ATTACK_NOTI":     6,
		"ATTACK_PLAYER_NOTI":         7,
		"PLAYER_ATTACKED_NOTI":       8,
		"PLAYER_DEFENCE_NOTI":        9,
		"PLAYER_ATTACK_DEFENCE_NOTI": 10,
		"LOGIN_NOTI":                 11,
	}
)

func (x Notification) Enum() *Notification {
	p := new(Notification)
	*p = x
	return p
}

func (x Notification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Notification) Descriptor() protoreflect.EnumDescriptor {
	return file_orc_client_proto_enumTypes[1].Descriptor()
}

func (Notification) Type() protoreflect.EnumType {
	return &file_orc_client_proto_enumTypes[1]
}

func (x Notification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Notification.Descriptor instead.
func (Notification) EnumDescriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{1}
}

type Direction int32

const (
	Direction_NONE_DIR   Direction = 0
	Direction_NORTH      Direction = 1
	Direction_NORTH_EAST Direction = 2
	Direction_EAST       Direction = 3
	Direction_EAST_SOUTH Direction = 4
	Direction_SOUTH      Direction = 5
	Direction_SOUTH_WEST Direction = 6
	Direction_WEST       Direction = 7
	Direction_WEST_NORTH Direction = 8
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "NONE_DIR",
		1: "NORTH",
		2: "NORTH_EAST",
		3: "EAST",
		4: "EAST_SOUTH",
		5: "SOUTH",
		6: "SOUTH_WEST",
		7: "WEST",
		8: "WEST_NORTH",
	}
	Direction_value = map[string]int32{
		"NONE_DIR":   0,
		"NORTH":      1,
		"NORTH_EAST": 2,
		"EAST":       3,
		"EAST_SOUTH": 4,
		"SOUTH":      5,
		"SOUTH_WEST": 6,
		"WEST":       7,
		"WEST_NORTH": 8,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_orc_client_proto_enumTypes[2].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_orc_client_proto_enumTypes[2]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{2}
}

type PlayerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X        float64   `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y        float64   `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Dir      Direction `protobuf:"varint,4,opt,name=dir,proto3,enum=orc.Direction" json:"dir,omitempty"`
	RemainHp int32     `protobuf:"varint,5,opt,name=remain_hp,json=remainHp,proto3" json:"remain_hp,omitempty"`
	MaxHp    int32     `protobuf:"varint,6,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
}

func (x *PlayerMessage) Reset() {
	*x = PlayerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMessage) ProtoMessage() {}

func (x *PlayerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMessage.ProtoReflect.Descriptor instead.
func (*PlayerMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerMessage) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerMessage) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerMessage) GetDir() Direction {
	if x != nil {
		return x.Dir
	}
	return Direction_NONE_DIR
}

func (x *PlayerMessage) GetRemainHp() int32 {
	if x != nil {
		return x.RemainHp
	}
	return 0
}

func (x *PlayerMessage) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

type ProjectileMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X     float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y     float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Angle int32   `protobuf:"varint,4,opt,name=angle,proto3" json:"angle,omitempty"`
}

func (x *ProjectileMessage) Reset() {
	*x = ProjectileMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectileMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectileMessage) ProtoMessage() {}

func (x *ProjectileMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectileMessage.ProtoReflect.Descriptor instead.
func (*ProjectileMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectileMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectileMessage) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProjectileMessage) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ProjectileMessage) GetAngle() int32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type MoveJogReqMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dir Direction `protobuf:"varint,1,opt,name=dir,proto3,enum=orc.Direction" json:"dir,omitempty"`
}

func (x *MoveJogReqMessage) Reset() {
	*x = MoveJogReqMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveJogReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveJogReqMessage) ProtoMessage() {}

func (x *MoveJogReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveJogReqMessage.ProtoReflect.Descriptor instead.
func (*MoveJogReqMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{2}
}

func (x *MoveJogReqMessage) GetDir() Direction {
	if x != nil {
		return x.Dir
	}
	return Direction_NONE_DIR
}

type EnterPlayerNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *PlayerMessage `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *EnterPlayerNotiMessage) Reset() {
	*x = EnterPlayerNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterPlayerNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterPlayerNotiMessage) ProtoMessage() {}

func (x *EnterPlayerNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterPlayerNotiMessage.ProtoReflect.Descriptor instead.
func (*EnterPlayerNotiMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{3}
}

func (x *EnterPlayerNotiMessage) GetPlayer() *PlayerMessage {
	if x != nil {
		return x.Player
	}
	return nil
}

type EnterProjectileNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Projectile *ProjectileMessage `protobuf:"bytes,1,opt,name=projectile,proto3" json:"projectile,omitempty"`
}

func (x *EnterProjectileNotiMessage) Reset() {
	*x = EnterProjectileNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterProjectileNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterProjectileNotiMessage) ProtoMessage() {}

func (x *EnterProjectileNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterProjectileNotiMessage.ProtoReflect.Descriptor instead.
func (*EnterProjectileNotiMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{4}
}

func (x *EnterProjectileNotiMessage) GetProjectile() *ProjectileMessage {
	if x != nil {
		return x.Projectile
	}
	return nil
}

type WelcomePlayerNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyId    int64            `protobuf:"varint,1,opt,name=my_id,json=myId,proto3" json:"my_id,omitempty"`
	Players []*PlayerMessage `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *WelcomePlayerNotiMessage) Reset() {
	*x = WelcomePlayerNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomePlayerNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomePlayerNotiMessage) ProtoMessage() {}

func (x *WelcomePlayerNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomePlayerNotiMessage.ProtoReflect.Descriptor instead.
func (*WelcomePlayerNotiMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{5}
}

func (x *WelcomePlayerNotiMessage) GetMyId() int64 {
	if x != nil {
		return x.MyId
	}
	return 0
}

func (x *WelcomePlayerNotiMessage) GetPlayers() []*PlayerMessage {
	if x != nil {
		return x.Players
	}
	return nil
}

type LeaveObjectNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LeaveObjectNotiMessage) Reset() {
	*x = LeaveObjectNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveObjectNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveObjectNotiMessage) ProtoMessage() {}

func (x *LeaveObjectNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveObjectNotiMessage.ProtoReflect.Descriptor instead.
func (*LeaveObjectNotiMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveObjectNotiMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MoveObjectNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*MoveObjectNotiMessage_Object `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *MoveObjectNotiMessage) Reset() {
	*x = MoveObjectNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveObjectNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveObjectNotiMessage) ProtoMessage() {}

func (x *MoveObjectNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveObjectNotiMessage.ProtoReflect.Descriptor instead.
func (*MoveObjectNotiMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{7}
}

func (x *MoveObjectNotiMessage) GetObjects() []*MoveObjectNotiMessage_Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type ProjectileAttackNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId     int64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ProjectileId int64 `protobuf:"varint,2,opt,name=projectile_id,json=projectileId,proto3" json:"projectile_id,omitempty"`
}

func (x *ProjectileAttackNotiMessage) Reset() {
	*x = ProjectileAttackNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectileAttackNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectileAttackNotiMessage) ProtoMessage() {}

func (x *ProjectileAttackNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectileAttackNotiMessage.ProtoReflect.Descriptor instead.
func (*ProjectileAttackNotiMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectileAttackNotiMessage) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ProjectileAttackNotiMessage) GetProjectileId() int64 {
	if x != nil {
		return x.ProjectileId
	}
	return 0
}

type ShootProjectileReqMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Angle int32 `protobuf:"varint,1,opt,name=angle,proto3" json:"angle,omitempty"`
}

func (x *ShootProjectileReqMessage) Reset() {
	*x = ShootProjectileReqMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootProjectileReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootProjectileReqMessage) ProtoMessage() {}

func (x *ShootProjectileReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootProjectileReqMessage.ProtoReflect.Descriptor instead.
func (*ShootProjectileReqMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{9}
}

func (x *ShootProjectileReqMessage) GetAngle() int32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type AttackReqMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AttackReqMessage) Reset() {
	*x = AttackReqMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttackReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackReqMessage) ProtoMessage() {}

func (x *AttackReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackReqMessage.ProtoReflect.Descriptor instead.
func (*AttackReqMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{10}
}

type AttackPlayerNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64     `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Dir      Direction `protobuf:"varint,2,opt,name=dir,proto3,enum=orc.Direction" json:"dir,omitempty"`
}

func (x *AttackPlayerNotiMessage) Reset() {
	*x = AttackPlayerNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttackPlayerNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackPlayerNotiMessage) ProtoMessage() {}

func (x *AttackPlayerNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackPlayerNotiMessage.ProtoReflect.Descriptor instead.
func (*AttackPlayerNotiMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{11}
}

func (x *AttackPlayerNotiMessage) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *AttackPlayerNotiMessage) GetDir() Direction {
	if x != nil {
		return x.Dir
	}
	return Direction_NONE_DIR
}

type PlayerAttackedNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X        float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y        float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	RemainHp int32   `protobuf:"varint,4,opt,name=remain_hp,json=remainHp,proto3" json:"remain_hp,omitempty"`
}

func (x *PlayerAttackedNotiMessage) Reset() {
	*x = PlayerAttackedNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerAttackedNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAttackedNotiMessage) ProtoMessage() {}

func (x *PlayerAttackedNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAttackedNotiMessage.ProtoReflect.Descriptor instead.
func (*PlayerAttackedNotiMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerAttackedNotiMessage) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerAttackedNotiMessage) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerAttackedNotiMessage) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerAttackedNotiMessage) GetRemainHp() int32 {
	if x != nil {
		return x.RemainHp
	}
	return 0
}

type DefenceReqMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DefenceReqMessage) Reset() {
	*x = DefenceReqMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefenceReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefenceReqMessage) ProtoMessage() {}

func (x *DefenceReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefenceReqMessage.ProtoReflect.Descriptor instead.
func (*DefenceReqMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{13}
}

type PlayerDefenceNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X        float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y        float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *PlayerDefenceNotiMessage) Reset() {
	*x = PlayerDefenceNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerDefenceNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDefenceNotiMessage) ProtoMessage() {}

func (x *PlayerDefenceNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDefenceNotiMessage.ProtoReflect.Descriptor instead.
func (*PlayerDefenceNotiMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerDefenceNotiMessage) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerDefenceNotiMessage) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerDefenceNotiMessage) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerAttackDefenceNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X        float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y        float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	RemainHp int32   `protobuf:"varint,4,opt,name=remain_hp,json=remainHp,proto3" json:"remain_hp,omitempty"`
}

func (x *PlayerAttackDefenceNotiMessage) Reset() {
	*x = PlayerAttackDefenceNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerAttackDefenceNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAttackDefenceNotiMessage) ProtoMessage() {}

func (x *PlayerAttackDefenceNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAttackDefenceNotiMessage.ProtoReflect.Descriptor instead.
func (*PlayerAttackDefenceNotiMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerAttackDefenceNotiMessage) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerAttackDefenceNotiMessage) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerAttackDefenceNotiMessage) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerAttackDefenceNotiMessage) GetRemainHp() int32 {
	if x != nil {
		return x.RemainHp
	}
	return 0
}

type LoginReqMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LoginReqMessage) Reset() {
	*x = LoginReqMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReqMessage) ProtoMessage() {}

func (x *LoginReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReqMessage.ProtoReflect.Descriptor instead.
func (*LoginReqMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{16}
}

func (x *LoginReqMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginNotiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *LoginNotiMessage) Reset() {
	*x = LoginNotiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginNotiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginNotiMessage) ProtoMessage() {}

func (x *LoginNotiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginNotiMessage.ProtoReflect.Descriptor instead.
func (*LoginNotiMessage) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{17}
}

func (x *LoginNotiMessage) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type MoveObjectNotiMessage_Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X   float64   `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y   float64   `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Dir Direction `protobuf:"varint,4,opt,name=dir,proto3,enum=orc.Direction" json:"dir,omitempty"`
}

func (x *MoveObjectNotiMessage_Object) Reset() {
	*x = MoveObjectNotiMessage_Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_client_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveObjectNotiMessage_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveObjectNotiMessage_Object) ProtoMessage() {}

func (x *MoveObjectNotiMessage_Object) ProtoReflect() protoreflect.Message {
	mi := &file_orc_client_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveObjectNotiMessage_Object.ProtoReflect.Descriptor instead.
func (*MoveObjectNotiMessage_Object) Descriptor() ([]byte, []int) {
	return file_orc_client_proto_rawDescGZIP(), []int{7, 0}
}

func (x *MoveObjectNotiMessage_Object) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MoveObjectNotiMessage_Object) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveObjectNotiMessage_Object) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MoveObjectNotiMessage_Object) GetDir() Direction {
	if x != nil {
		return x.Dir
	}
	return Direction_NONE_DIR
}

var File_orc_client_proto protoreflect.FileDescriptor

var file_orc_client_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6f, 0x72, 0x63, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x6f, 0x72, 0x63, 0x22, 0x91, 0x01, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x20, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6f, 0x72, 0x63, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x5f, 0x68, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x48, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x78, 0x5f, 0x68, 0x70, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x78, 0x48, 0x70, 0x22, 0x55, 0x0a, 0x11, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x6e, 0x67,
	0x6c, 0x65, 0x22, 0x35, 0x0a, 0x11, 0x4d, 0x6f, 0x76, 0x65, 0x4a, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6f, 0x72, 0x63, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x64, 0x69, 0x72, 0x22, 0x44, 0x0a, 0x16, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x72, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22,
	0x54, 0x0a, 0x1a, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x72, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x69, 0x6c, 0x65, 0x22, 0x5d, 0x0a, 0x18, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x6d, 0x79, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x72, 0x63, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xac,
	0x01, 0x0a, 0x15, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x6f, 0x74,
	0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x72, 0x63, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x1a, 0x56, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x20, 0x0a, 0x03, 0x64,
	0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6f, 0x72, 0x63, 0x2e, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x64, 0x69, 0x72, 0x22, 0x5f, 0x0a,
	0x1b, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x31,
	0x0a, 0x19, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c,
	0x65, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x58, 0x0a, 0x17, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x03, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6f, 0x72, 0x63,
	0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x64, 0x69, 0x72, 0x22,
	0x71, 0x0a, 0x19, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65,
	0x64, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x5f,
	0x68, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x48, 0x70, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x66, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x53, 0x0a, 0x18, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x44, 0x65, 0x66, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x22, 0x76, 0x0a, 0x1e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x44, 0x65, 0x66, 0x65,
	0x6e, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x5f, 0x68, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x48, 0x70, 0x22, 0x25, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x35, 0x0a, 0x10, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x2a, 0x77, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x0c, 0x4e, 0x4f, 0x4e, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4a, 0x4f, 0x47, 0x5f, 0x52, 0x45, 0x51, 0x10,
	0x01, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x48, 0x4f, 0x4f, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4a, 0x45,
	0x43, 0x54, 0x49, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x41,
	0x54, 0x54, 0x41, 0x43, 0x4b, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x44,
	0x45, 0x46, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x05, 0x2a, 0xac, 0x02, 0x0a, 0x0c,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x4f, 0x4e, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x45,
	0x4e, 0x54, 0x45, 0x52, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x49,
	0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x57, 0x45, 0x4c, 0x43, 0x4f, 0x4d, 0x45, 0x5f, 0x50, 0x4c,
	0x41, 0x59, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x4c,
	0x45, 0x41, 0x56, 0x45, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x49,
	0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43,
	0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x4e, 0x54, 0x45,
	0x52, 0x5f, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x49, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x54,
	0x49, 0x10, 0x05, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x49, 0x4c,
	0x45, 0x5f, 0x41, 0x54, 0x54, 0x41, 0x43, 0x4b, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10, 0x06, 0x12,
	0x16, 0x0a, 0x12, 0x41, 0x54, 0x54, 0x41, 0x43, 0x4b, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10, 0x07, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x4c, 0x41, 0x59, 0x45,
	0x52, 0x5f, 0x41, 0x54, 0x54, 0x41, 0x43, 0x4b, 0x45, 0x44, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10,
	0x08, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x44, 0x45, 0x46, 0x45,
	0x4e, 0x43, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10, 0x09, 0x12, 0x1e, 0x0a, 0x1a, 0x50, 0x4c,
	0x41, 0x59, 0x45, 0x52, 0x5f, 0x41, 0x54, 0x54, 0x41, 0x43, 0x4b, 0x5f, 0x44, 0x45, 0x46, 0x45,
	0x4e, 0x43, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10, 0x0a, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x4f,
	0x47, 0x49, 0x4e, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x10, 0x0b, 0x2a, 0x83, 0x01, 0x0a, 0x09, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x4e, 0x45,
	0x5f, 0x44, 0x49, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x10,
	0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x5f, 0x45, 0x41, 0x53, 0x54, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x41, 0x53, 0x54, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x45,
	0x41, 0x53, 0x54, 0x5f, 0x53, 0x4f, 0x55, 0x54, 0x48, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x53,
	0x4f, 0x55, 0x54, 0x48, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x4f, 0x55, 0x54, 0x48, 0x5f,
	0x57, 0x45, 0x53, 0x54, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x45, 0x53, 0x54, 0x10, 0x07,
	0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x10, 0x08,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x6f, 0x72, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orc_client_proto_rawDescOnce sync.Once
	file_orc_client_proto_rawDescData = file_orc_client_proto_rawDesc
)

func file_orc_client_proto_rawDescGZIP() []byte {
	file_orc_client_proto_rawDescOnce.Do(func() {
		file_orc_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_orc_client_proto_rawDescData)
	})
	return file_orc_client_proto_rawDescData
}

var file_orc_client_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_orc_client_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_orc_client_proto_goTypes = []interface{}{
	(Request)(0),                           // 0: orc.Request
	(Notification)(0),                      // 1: orc.Notification
	(Direction)(0),                         // 2: orc.Direction
	(*PlayerMessage)(nil),                  // 3: orc.PlayerMessage
	(*ProjectileMessage)(nil),              // 4: orc.ProjectileMessage
	(*MoveJogReqMessage)(nil),              // 5: orc.MoveJogReqMessage
	(*EnterPlayerNotiMessage)(nil),         // 6: orc.EnterPlayerNotiMessage
	(*EnterProjectileNotiMessage)(nil),     // 7: orc.EnterProjectileNotiMessage
	(*WelcomePlayerNotiMessage)(nil),       // 8: orc.WelcomePlayerNotiMessage
	(*LeaveObjectNotiMessage)(nil),         // 9: orc.LeaveObjectNotiMessage
	(*MoveObjectNotiMessage)(nil),          // 10: orc.MoveObjectNotiMessage
	(*ProjectileAttackNotiMessage)(nil),    // 11: orc.ProjectileAttackNotiMessage
	(*ShootProjectileReqMessage)(nil),      // 12: orc.ShootProjectileReqMessage
	(*AttackReqMessage)(nil),               // 13: orc.AttackReqMessage
	(*AttackPlayerNotiMessage)(nil),        // 14: orc.AttackPlayerNotiMessage
	(*PlayerAttackedNotiMessage)(nil),      // 15: orc.PlayerAttackedNotiMessage
	(*DefenceReqMessage)(nil),              // 16: orc.DefenceReqMessage
	(*PlayerDefenceNotiMessage)(nil),       // 17: orc.PlayerDefenceNotiMessage
	(*PlayerAttackDefenceNotiMessage)(nil), // 18: orc.PlayerAttackDefenceNotiMessage
	(*LoginReqMessage)(nil),                // 19: orc.LoginReqMessage
	(*LoginNotiMessage)(nil),               // 20: orc.LoginNotiMessage
	(*MoveObjectNotiMessage_Object)(nil),   // 21: orc.MoveObjectNotiMessage.Object
}
var file_orc_client_proto_depIdxs = []int32{
	2,  // 0: orc.PlayerMessage.dir:type_name -> orc.Direction
	2,  // 1: orc.MoveJogReqMessage.dir:type_name -> orc.Direction
	3,  // 2: orc.EnterPlayerNotiMessage.player:type_name -> orc.PlayerMessage
	4,  // 3: orc.EnterProjectileNotiMessage.projectile:type_name -> orc.ProjectileMessage
	3,  // 4: orc.WelcomePlayerNotiMessage.players:type_name -> orc.PlayerMessage
	21, // 5: orc.MoveObjectNotiMessage.objects:type_name -> orc.MoveObjectNotiMessage.Object
	2,  // 6: orc.AttackPlayerNotiMessage.dir:type_name -> orc.Direction
	2,  // 7: orc.MoveObjectNotiMessage.Object.dir:type_name -> orc.Direction
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_orc_client_proto_init() }
func file_orc_client_proto_init() {
	if File_orc_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orc_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectileMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveJogReqMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterPlayerNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterProjectileNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WelcomePlayerNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveObjectNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveObjectNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectileAttackNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootProjectileReqMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttackReqMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttackPlayerNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerAttackedNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefenceReqMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerDefenceNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerAttackDefenceNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReqMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginNotiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_client_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveObjectNotiMessage_Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orc_client_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orc_client_proto_goTypes,
		DependencyIndexes: file_orc_client_proto_depIdxs,
		EnumInfos:         file_orc_client_proto_enumTypes,
		MessageInfos:      file_orc_client_proto_msgTypes,
	}.Build()
	File_orc_client_proto = out.File
	file_orc_client_proto_rawDesc = nil
	file_orc_client_proto_goTypes = nil
	file_orc_client_proto_depIdxs = nil
}
